# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmiC5jlSa_alkVRMnoLHR9fWz7Q5T7zX
"""

List = input().split()
sum = 0
for i in List:
  if int(i) < 60:
    sum += 1
print(sum)

total = 0
for i in List:
  total += int(i)

average = total / len(List)
print(f"{average:.2f}")

